major = ["chariot", "chariot_inv", "death", "death_inv", "devil", "devil_inv", "emperor", "emperor_inv", "empress", "empress_inv", "fool", "fool_inv", "hanged", "hanged_inv", "hermit", "hermit_inv", "hierophant", "hierophant_inv", "hpriestess", "hpriestess_inv",  "judgment", "judgment_inv", "justice", "justice_inv", "lovers", "lovers_inv", "magician", "magician_inv", "moon", "moon_inv", "wheel", "wheel_inv", "world", "world_inv", "temperance", "temperance_inv", "tower", "tower_inv", "star", "star_inv", "strength", "strength_inv", "sun", "sun_inv"]

minor = ["cups01", "cups01_inv", "cups02", "cups02_inv", "cups03", "cups03_inv", "cups04", "cups04_inv", "cups05", "cups05_inv", "cups06", "cups06_inv", "cups07", "cups07_inv", "cups08", "cups08_inv", "cups09", "cups09_inv", "cups10", "cups10_inv", "cups11", "cups11_inv", "cups12", "cups12_inv", "cups13", "cups13_inv", "cups14", "cups14_inv", "wands01", "wands01_inv", "wands02", "wands02_inv", "wands03", "wands03_inv", "wands04", "wands04_inv", "wands05", "wands05_inv", "wands06", "wands06_inv", "wands07", "wands07_inv", "wands08", "wands08_inv", "wands09", "wands09_inv", "wands10", "wands10_inv", "wands11", "wands11_inv", "wands12", "wands12_inv", "wands13", "wands13_inv", "wands14", "wands14_inv", "pentacles01", "pentacles01_inv", "pentacles02", "pentacles02_inv", "pentacles03", "pentacles03_inv", "pentacles04", "pentacles04_inv", "pentacles05", "pentacles05_inv", "pentacles06", "pentacles06_inv", "pentacles07", "pentacles07_inv", "pentacles08", "pentacles08_inv", "pentacles09", "pentacles09_inv", "pentacles10", "pentacles10_inv", "pentacles11", "pentacles11_inv", "pentacles12", "pentacles12_inv", "pentacles13", "pentacles13_inv", "pentacles14", "pentacles14_inv", "swords01", "swords01_inv", "swords02", "swords02_inv", "swords03", "swords03_inv", "swords04", "swords04_inv", "swords05", "swords05_inv", "swords06", "swords06_inv", "swords07", "swords07_inv", "swords08", "swords08_inv", "swords09", "swords09_inv", "swords10", "swords10_inv", "swords11", "swords11_inv", "swords12", "swords12_inv", "swords13", "swords13_inv", "swords14", "swords14_inv"]
 
 all = ["chariot", "chariot_inv", "death", "death_inv", "devil", "devil_inv", "emperor", "emperor_inv", "empress", "empress_inv", "fool", "fool_inv", "hanged", "hanged_inv", "hermit", "hermit_inv", "hierophant", "hierophant_inv", "hpriestess", "hpriestess_inv",  "judgment", "judgment_inv", "justice", "justice_inv", "lovers", "lovers_inv", "magician", "magician_inv", "moon", "moon_inv", "wheel", "wheel_inv", "world", "world_inv", "temperance", "temperance_inv", "tower", "tower_inv", "star", "star_inv", "strength", "strength_inv", "sun", "sun_inv", "cups01", "cups01_inv", "cups02", "cups02_inv", "cups03", "cups03_inv", "cups04", "cups04_inv", "cups05", "cups05_inv", "cups06", "cups06_inv", "cups07", "cups07_inv", "cups08", "cups08_inv", "cups09", "cups09_inv", "cups10", "cups10_inv", "cups11", "cups11_inv", "cups12", "cups12_inv", "cups13", "cups13_inv", "cups14", "cups14_inv", "wands01", "wands01_inv", "wands02", "wands02_inv", "wands03", "wands03_inv", "wands04", "wands04_inv", "wands05", "wands05_inv", "wands06", "wands06_inv", "wands07", "wands07_inv", "wands08", "wands08_inv", "wands09", "wands09_inv", "wands10", "wands10_inv", "wands11", "wands11_inv", "wands12", "wands12_inv", "wands13", "wands13_inv", "wands14", "wands14_inv", "pentacles01", "pentacles01_inv", "pentacles02", "pentacles02_inv", "pentacles03", "pentacles03_inv", "pentacles04", "pentacles04_inv", "pentacles05", "pentacles05_inv", "pentacles06", "pentacles06_inv", "pentacles07", "pentacles07_inv", "pentacles08", "pentacles08_inv", "pentacles09", "pentacles09_inv", "pentacles10", "pentacles10_inv", "pentacles11", "pentacles11_inv", "pentacles12", "pentacles12_inv", "pentacles13", "pentacles13_inv", "pentacles14", "pentacles14_inv", "swords01", "swords01_inv", "swords02", "swords02_inv", "swords03", "swords03_inv", "swords04", "swords04_inv", "swords05", "swords05_inv", "swords06", "swords06_inv", "swords07", "swords07_inv", "swords08", "swords08_inv", "swords09", "swords09_inv", "swords10", "swords10_inv", "swords11", "swords11_inv", "swords12", "swords12_inv", "swords13", "swords13_inv", "swords14", "swords14_inv"]

 puts "There are #{major.length} names in the Major array. This means there are #{major.length / 2} cards in the deck."
puts "There are #{minor.length} names in the Minor array. This means there are #{minor.length / 2} cards in the deck." 
puts "There are #{all.length} names in the All array. This means there are #{all.length / 2} cards in both decks."
