# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



#Major Arcana Seeds

Card.create(arcana: 'ma', name: 'Inverted Fool', theme: 'Resistance', meaning: 'Resistance, stuck, foolishness, risk-taking, recklessness', imagefile: 'ma00-fool_inv.jpg')
Card.create(arcana: 'ma', name: 'Fool', theme: 'Beginning', meaning: 'Beginning, innocence, journey, spontaneity, free spirit', imagefile: 'ma00-fool.jpg')
Card.create(arcana: 'ma', name: 'Inverted Magician', theme: 'Ineptitude', meaning: 'Ineptitude, manipulation, poor planning, latent talents', imagefile: 'ma01-magician_inv.jpg')
Card.create(arcana: 'ma', name: 'Magician', theme: 'Intention', meaning: 'Intention, focus, will, power, skill, purpose, creativity, resourcefulness', imagefile: 'ma01-magician.jpg')
Card.create(arcana: 'ma', name: 'Inverted High Priestess', theme: 'Superficial', meaning: 'Superficial, hidden agendas, need to listen to inner voice', imagefile: 'ma02-highpriestess_inv.jpg')
Card.create(arcana: 'ma', name: 'High Priestess', theme: 'Intuition', meaning: 'Intuition, higher powers, wisdom, secrets, subconscious mind', imagefile: 'ma02-highpriestess.jpg')
Card.create(arcana: 'ma', name: 'Inverted Empress', theme: 'Infertility', meaning: 'Infertility, creative block, over-indulgent, material loss, insecure', imagefile: 'ma03-empress_inv.jpg')
Card.create(arcana: 'ma', name: 'Empress', theme: 'Fertility', meaning: 'Fertility, mother, lover, nature, protection, abundance', imagefile: 'ma03-empress.jpg')
Card.create(arcana: 'ma', name: 'Inverted Emperor', theme: 'Tyranny', meaning: 'Domination, force, excessive control, rigidity, inflexibility', imagefile: 'ma04-emperor_inv.jpg')
Card.create(arcana: 'ma', name: 'Emperor', theme: 'Authority', meaning: 'Authority, father-figure, leadership, structure, logic, power', imagefile: 'ma04-emperor.jpg')
Card.create(arcana: 'ma', name: 'Inverted Hierophant', theme: 'Rebellion', meaning: 'Rebellion, restriction, unethical, challenging authority', imagefile: 'ma05-hierophant_inv.jpg')
Card.create(arcana: 'ma', name: 'Hierophant', theme: 'Organizations', meaning: 'Organizations, religion, group identification, social rules, tradition, school', imagefile: 'ma05-hierophant.jpg')
Card.create(arcana: 'ma', name: 'Inverted Lovers', theme: 'Disharmony', meaning: 'Disharmony, imbalance, struggle, loneliness, miscommunication', imagefile: 'ma06-lovers_inv.jpg')
Card.create(arcana: 'ma', name: 'Lovers', theme: 'Relationships', meaning: 'Relationships, love, communication, union, harmony, choices', imagefile: 'ma06-lovers.jpg')
Card.create(arcana: 'ma', name: 'Inverted Chariot', theme: 'Domineering', meaning: 'Domineering, accidents, delay, lack of control and direction, aggression', imagefile: 'ma07-chariot_inv.jpg')
Card.create(arcana: 'ma', name: 'Chariot', theme: 'Direction', meaning: 'Direction, control, will power, victory, ambition, travel', imagefile: 'ma07-chariot.jpg')
Card.create(arcana: 'ma', name: 'Inverted Strength', theme: 'Weakness', meaning: 'Weakness, self-doubt, egoism, lack of self-discipline, suppressed urges', imagefile: 'ma08-strength_inv.jpg')
Card.create(arcana: 'ma', name: 'Strength', theme: 'Fortitude', meaning: 'Fortitude, inner strength, love, patience, compassion', imagefile: 'ma08-strength.jpg')
Card.create(arcana: 'ma', name: 'Inverted Hermit', theme: 'Antisocial', meaning: 'Isolation, loneliness, withdrawal, fearful, abandonment', imagefile: 'ma09-hermit_inv.jpg')
Card.create(arcana: 'ma', name: 'Hermit', theme: 'Solitude', meaning: 'Solitude, soul-searching, introspection, being alone, inner guidance', imagefile: 'ma09-hermit.jpg')
Card.create(arcana: 'ma', name: 'Inverted Wheel of Fortune', theme: 'Instability', meaning: 'Instability, bad timing, stress, rapid change, out of control', imagefile: 'ma10-wheelfortune_inv.jpg')
Card.create(arcana: 'ma', name: 'Wheel of Fortune', theme: 'Fate', meaning: 'Fate, good luck, karma, life cycles, destiny, changes, big picture', imagefile: 'ma10-wheelfortune.jpg')
Card.create(arcana: 'ma', name: 'Inverted Justice', theme: 'Injustice', meaning: 'Injustice, unfairness, bias, shame, indecision, dishonesty', imagefile: 'ma11-justice_inv.jpg')
Card.create(arcana: 'ma', name: 'Justice', theme: 'Justice', meaning: 'Justice, fairness, truth, law, logic, balance', imagefile: 'ma11-justice.jpg')
Card.create(arcana: 'ma', name: 'Inverted Hanged Man', theme: 'Falseness', meaning: 'Martyrdom, ulterior motives, selfish, unmotivated', imagefile: 'ma12-hangedman_inv.jpg')
Card.create(arcana: 'ma', name: 'Hanged Man', theme: 'Sacrifice', meaning: 'Sacrifice, restriction, letting go, evaluation, new perspective', imagefile: 'ma12-hangedman.jpg')
Card.create(arcana: 'ma', name: 'Inverted Death', theme: 'Distressed', meaning: 'Distressed, depression, unable to move on, recovery', imagefile: 'ma13-death_inv.jpg')
Card.create(arcana: 'ma', name: 'Death', theme: 'Transformation', meaning: 'Transformation, ending, beginning, transition', imagefile: 'ma13-death.jpg')
Card.create(arcana: 'ma', name: 'Inverted Temperance', theme: 'Imbalance', meaning: 'Imbalance, extremes, conflicts, lack of long-term vision', imagefile: 'ma14-temperance_inv.jpg')
Card.create(arcana: 'ma', name: 'Temperance', theme: 'Balance', meaning: 'Balance, moderation, mix, patience, adjusting', imagefile: 'ma14-temperance.jpg')
Card.create(arcana: 'ma', name: 'Inverted Devil', theme: 'Extremes', meaning: 'Extremes, hedonism, breaking free, power reclaimed', imagefile: 'ma15-devil_inv.jpg')
Card.create(arcana: 'ma', name: 'Devil', theme: 'Bondage', meaning: 'Bondage, fear, self-restriction, addiction, lust, dark side of self', imagefile: 'ma15-devil.jpg')
Card.create(arcana: 'ma', name: 'Inverted Tower', theme: 'Precaution', meaning: 'Precaution, avoidance of disaster, fear of change', imagefile: 'ma16-tower_inv.jpg')
Card.create(arcana: 'ma', name: 'Tower', theme: 'Destruction', meaning: 'Destruction, false securities, upheaval, sudden change, wake-up call', imagefile: 'ma16-tower.jpg')
Card.create(arcana: 'ma', name: 'Inverted Star', theme: 'Hopeless', meaning: 'Hopeless, despair, sabotaging, lacking creativity', imagefile: 'ma17-star_inv.jpg')
Card.create(arcana: 'ma', name: 'Star', theme: 'Hope', meaning: 'Hope, guidance, relief, inspiration, harmony', imagefile: 'ma17-star.jpg')
Card.create(arcana: 'ma', name: 'Inverted Moon', theme: 'Deception', meaning: 'Deception, irrationality, disbelief, confusion, blocked intuition', imagefile: 'ma18-moon_inv.jpg')
Card.create(arcana: 'ma', name: 'Moon', theme: 'Illusion', meaning: 'Illusion, intuition, unknown, fear, subconscious', imagefile: 'ma18-moon.jpg')
Card.create(arcana: 'ma', name: 'Inverted Sun', theme: 'Discontentment', meaning: 'Discontentment, clouded perspective, dull feelings, loss', imagefile: 'ma19-sun_inv.jpg')
Card.create(arcana: 'ma', name: 'Sun', theme: 'Illumination', meaning: 'Illumination, clarity, fun, warmth, success, vitality, clarity', imagefile: 'ma19-sun.jpg')
Card.create(arcana: 'ma', name: 'Inverted Judgment', theme: 'Avoidance', meaning: 'Avoidance, stagnation, refusal of self-examination, indecision', imagefile: 'ma20-judgement_inv.jpg')
Card.create(arcana: 'ma', name: 'Judgment', theme: 'Awakening', meaning: 'Awakening, rebirth, inner calling, new perspective', imagefile: 'ma20-judgement.jpg')
Card.create(arcana: 'ma', name: 'Inverted World', theme: 'Pending', meaning: 'Pending, obstacles, incomplete project, distraction', imagefile: 'ma21-world_inv.jpg')
Card.create(arcana: 'ma', name: 'World', theme: 'Enlightenment', meaning: 'Enlightenment, completion, travel, perfect unity, accomplishment', imagefile: 'ma21-world.jpg')
