# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Card.create(arcana: 'ma', name: 'Fool', theme: 'Beginning', meaning: 'Beginning, innocence, foolishness, journey, spontaneity, and free spirit', imagefile: 'ma00-fool.jpg')
Card.create(arcana: 'ma', name: 'Magician', theme: 'Intention', meaning: 'Intention, focus, will, power, skill, purpose, creativity, and resourcefulness', imagefile: 'ma01-magician.jpg')
Card.create(arcana: 'ma', name: 'High Priestess', theme: 'Intuition', meaning: 'Intuition, higher powers, wisdom, secrets, and subconscious mind', imagefile: 'ma02-highpriestess.jpg')
Card.create(arcana: 'ma', name: 'Empress', theme: 'Fertility', meaning: 'Fertility, mother, lover, nature, protection, and abundance', imagefile: 'ma03-empress.jpg')
Card.create(arcana: 'ma', name: 'Emperor', theme: 'Authority', meaning: 'Authority, father-figure, leadership, structure, logic, and power', imagefile: 'ma04-emperor.jpg')
Card.create(arcana: 'ma', name: 'Hierophant', theme: 'Organizations', meaning: 'Organizations, religion, group identification, social rules, tradition, and school', imagefile: 'ma05-hierophant.jpg')
Card.create(arcana: 'ma', name: 'Lovers', theme: 'Relationships', meaning: 'Relationships, love, communication, union, harmony, and choices', imagefile: 'ma06-lovers.jpg')
Card.create(arcana: 'ma', name: 'Chariot', theme: 'Direction', meaning: 'Direction, control, will power, victory, ambition, and travel', imagefile: 'ma07-chariot.jpg')
Card.create(arcana: 'ma', name: 'Strength', theme: 'Fortitude', meaning: 'Fortitude, inner strength, love, patience, and compassion', imagefile: 'ma08-strength.jpg')
Card.create(arcana: 'ma', name: 'Hermit', theme: 'Solitude', meaning: 'Solitude, soul-searching, introspection, being alone, and inner guidance', imagefile: 'ma09-hermit.jpg')
Card.create(arcana: 'ma', name: 'Wheel of Fortune', theme: 'Fate', meaning: 'Fate, good luck, karma, life cycles, destiny, changes, and big picture', imagefile: 'ma10-wheelfortune.jpg')
Card.create(arcana: 'ma', name: 'Justice', theme: 'Justice', meaning: 'Justice, fairness, truth, law, logic, and balance', imagefile: 'ma11-justice.jpg')
Card.create(arcana: 'ma', name: 'Hanged Man', theme: 'Sacrifice', meaning: 'Sacrifice, restriction, letting go, evaluation, and new perspective', imagefile: 'ma12-hangedman.jpg')
Card.create(arcana: 'ma', name: 'Death', theme: 'Transformation', meaning: 'Transformation, ending, beginning, and transition', imagefile: 'ma13-death.jpg')
Card.create(arcana: 'ma', name: 'Temperance', theme: 'Balance', meaning: 'Balance, moderation, mix, patience, and adjusting', imagefile: 'ma14-temperance.jpg')
Card.create(arcana: 'ma', name: 'Devil', theme: 'Bondage', meaning: 'Bondage, fear, self-restriction, addiction, lust, and dark side of self', imagefile: 'ma15-devil.jpg')
Card.create(arcana: 'ma', name: 'Tower', theme: 'Destruction', meaning: 'Destruction, false securities, upheaval, sudden change, and wake-up call', imagefile: 'ma16-tower.jpg')
Card.create(arcana: 'ma', name: 'Star', theme: 'Hope', meaning: 'Hope, guidance, relief, inspiration, and harmony', imagefile: 'ma17-star.jpg')
Card.create(arcana: 'ma', name: 'Moon', theme: 'Illusion', meaning: 'Illusion, intuition, unknown, fear, and subconscious', imagefile: 'ma18-moon.jpg')
Card.create(arcana: 'ma', name: 'Sun', theme: 'Illumination', meaning: 'Illumination, clarity, fun, warmth, success, vitality, and clarity', imagefile: 'ma19-sun.jpg')
Card.create(arcana: 'ma', name: 'Judgment', theme: 'Awakening', meaning: 'Awakening, rebirth, inner calling, and new perspective', imagefile: 'ma20-judgment.jpg')
Card.create(arcana: 'ma', name: 'World', theme: 'Enlightenment', meaning: 'Enlightenment, completion, travel, perfect unity, and accomplishment', imagefile: 'ma21-world.jpg')
Card.create(arcana: 'mi', name: 'Ace of Cups', theme: 'Creation', meaning: 'New job, opportunity or business, creativity, and action', imagefile: 'mi-cups01ace.jpg')
Card.create(arcana: 'mi', name: 'Two of Cups', theme: 'Partnership', meaning: 'Personal power, strength, success, support, and restlessness', imagefile: 'mi-cups02.jpg')
Card.create(arcana: 'mi', name: 'Three of Cups', theme: 'Celebration', meaning: 'Celebration, team, female friends, and success', imagefile: 'mi-cups03.jpg')
Card.create(arcana: 'mi', name: 'Four of Cups', theme: 'Boredom', meaning: 'Reflection, absorption, apathy, stuck, and anti-social', imagefile: 'mi-cups04.jpg')
Card.create(arcana: 'mi', name: 'Five of Cups', theme: 'Depression', meaning: 'Loss, regret, living in past, let down, sadness, and grief', imagefile: 'mi-cups05.jpg')
Card.create(arcana: 'mi', name: 'Six of Cups', theme: 'Nostalgia', meaning: 'Happy memories, people from past, childlike, children, and inner child', imagefile: 'mi-cups06.jpg')
Card.create(arcana: 'mi', name: 'Seven of Cups', theme: 'Day Dreaming', meaning: 'Choices, decisions, focus, confusion, and the unknown', imagefile: 'mi-cups07.jpg')
Card.create(arcana: 'mi', name: 'Eight of Cups', theme: 'Unfulfilled', meaning: 'Walking away, new direction, no turning back, and burning bridges', imagefile: 'mi-cups08.jpg')
Card.create(arcana: 'mi', name: 'Nine of Cups', theme: 'Fulfillment', meaning: 'Happiness, contentment, smugness, and satisfaction', imagefile: 'mi-cups09.jpg')
Card.create(arcana: 'mi', name: 'Ten of Cups', theme: 'Happiness', meaning: 'Family happiness, blessings, love, contentment, and children', imagefile: 'mi-cups10.jpg')
Card.create(arcana: 'mi', name: 'Page of Cups', theme: 'Emotions', meaning: 'Birth, pregnancy, new project, labour of love, creativity, and ideas', imagefile: 'mi-cups11page.jpg')
Card.create(arcana: 'mi', name: 'Knight of Cups', theme: 'Emotions', meaning: 'Sensitive, romantic, emotional, loving, caring, and sensitive', imagefile: 'mi-cups12knight.jpg')
Card.create(arcana: 'mi', name: 'Queen of Cups', theme: 'Emotions', meaning: 'Sensitive, intuitive, caring, gentle, artistic, compassion, and emotions', imagefile: 'mi-cups13queen.jpg')
Card.create(arcana: 'mi', name: 'King of Cups', theme: 'Emotions', meaning: 'Loving, deep feelings, dreamer, gentle, and creative', imagefile: 'mi-cups14king.jpg')
Card.create(arcana: 'mi', name: 'Ace of Pentacles', theme: 'Prosperity', meaning: 'New source of money, financial opportunity, and regular money flow', imagefile: 'mi-pentacle01ace.jpg')
Card.create(arcana: 'mi', name: 'Two of Pentacles', theme: 'Juggling', meaning: 'Juggling money and life, going round in circles, and busy-ness', imagefile: 'mi-pentacle02.jpg')
Card.create(arcana: 'mi', name: 'Three of Pentacles', theme: 'Work', meaning: 'Learning, new skills, studying, apprentice, expert, and foundations', imagefile: 'mi-pentacle03.jpg')
Card.create(arcana: 'mi', name: 'Four of Pentacles', theme: 'Wealth', meaning: 'Hold onto money, budget, stuck, and lack of flow', imagefile: 'mi-pentacle04.jpg')
Card.create(arcana: 'mi', name: 'Five of Pentacles', theme: 'Poverty', meaning: 'Lack, financial hardship, struggle, hopeless, and spiritual poverty', imagefile: 'mi-pentacle05.jpg')
Card.create(arcana: 'mi', name: 'Six of Pentacles', theme: 'Generosity', meaning: 'Plenty, abundance, charity, financial help, and giving', imagefile: 'mi-pentacle06.jpg')
Card.create(arcana: 'mi', name: 'Seven of Pentacles', theme: 'Patience', meaning: 'Fruits of your labours, earned success, keep going, and evaluation', imagefile: 'mi-pentacle07.jpg')
Card.create(arcana: 'mi', name: 'Eight of Pentacles', theme: 'Education', meaning: 'Job satisfaction, making money, creativity, and progress', imagefile: 'mi-pentacle08.jpg')
Card.create(arcana: 'mi', name: 'Nine of Pentacles', theme: 'Luxury', meaning: 'Affluence, stability, security, prosperity, and self reliance', imagefile: 'mi-pentacle09.jpg')
Card.create(arcana: 'mi', name: 'Ten of Pentacles', theme: 'Legacy', meaning: 'Affluence, inheritance, family money, and sum of money', imagefile: 'mi-pentacle10.jpg')
Card.create(arcana: 'mi', name: 'Page of Pentacles', theme: 'Practicality', meaning: 'Practical, business ideas, physical enjoyment, attract resources, and earth sign child', imagefile: 'mi-pentacle11page.jpg')
Card.create(arcana: 'mi', name: 'Knight of Pentacles', theme: 'Practicality', meaning: 'Fixed, inflexible, finest of everything, stubborn, cautious, practical, hard worker, and disliking change', imagefile: 'mi-pentacle12knight.jpg')
Card.create(arcana: 'mi', name: 'Queen of Pentacles', theme: 'Practicality', meaning: 'Practical, business like, organized, stability, connection with earth and nature, and homely', imagefile: 'mi-pentacle13queen.jpg')
Card.create(arcana: 'mi', name: 'King of Pentacles', theme: 'Practicality', meaning: 'Business person, money, financial dealings, caution, and checking things carefully', imagefile: 'mi-pentacle14king.jpg')
Card.create(arcana: 'mi', name: 'Ace of Swords', theme: 'Breakthrough', meaning: 'Ideas, new beginnings, success, willpower, and focus', imagefile: 'mi-swords01ace.jpg')
Card.create(arcana: 'mi', name: 'Two of Swords', theme: 'Diplomacy', meaning: 'Indecision, lack of clarity, confusion, worry, and stress', imagefile: 'mi-swords02.jpg')
Card.create(arcana: 'mi', name: 'Three of Swords', theme: 'Grief', meaning: 'Arguments, heart-ache, sorrow, and conflict', imagefile: 'mi-swords03.jpg')
Card.create(arcana: 'mi', name: 'Four of Swords', theme: 'Recuperation', meaning: 'Recovery, retreat, de-stress, solitude, and time out', imagefile: 'mi-swords04.jpg')
Card.create(arcana: 'mi', name: 'Five of Swords', theme: 'Cruelty', meaning: 'Conflict, victory, strong adversary, and hollow victory', imagefile: 'mi-swords05.jpg')
Card.create(arcana: 'mi', name: 'Six of Swords', theme: 'Passage', meaning: 'Better conditions, look beyond current pain, and moving forward', imagefile: 'mi-swords06.jpg')
Card.create(arcana: 'mi', name: 'Seven of Swords', theme: 'Stealth', meaning: 'Theft, loss, sneaking away, underhand, cunning, and someone taking', imagefile: 'mi-swords07.jpg')
Card.create(arcana: 'mi', name: 'Eight of Swords', theme: 'Crisis', meaning: 'Restriction, limitations, obstacles, and trapped', imagefile: 'mi-swords08.jpg')
Card.create(arcana: 'mi', name: 'Nine of Swords', theme: 'Nightmare', meaning: 'Grief, despair, distress, desolation, illness, and stress', imagefile: 'mi-swords09.jpg')
Card.create(arcana: 'mi', name: 'Ten of Swords', theme: 'Misfortune', meaning: 'Endings and beginnings, let down, anxiety, and stabbed in the back', imagefile: 'mi-swords10.jpg')
Card.create(arcana: 'mi', name: 'Page of Swords', theme: 'Intellect', meaning: 'Childlike, temperamental, headstrong, aggressive, and defensive', imagefile: 'mi-swords11page.jpg')
Card.create(arcana: 'mi', name: 'Knight of Swords', theme: 'Intellect', meaning: 'Rushing, risk-taking, lack of thought, speed, impulsive, and headstrong', imagefile: 'mi-swords12knight.jpg')
Card.create(arcana: 'mi', name: 'Queen of Swords', theme: 'Intellect', meaning: 'Tough, independent, widow, honest, shrewd, and straight-talking', imagefile: 'mi-swords13queen.jpg')
Card.create(arcana: 'mi', name: 'King of Swords', theme: 'Intellect', meaning: 'Businessman, honest, efficient, detail, logical, and analytical', imagefile: 'mi-swords14king.jpg')
Card.create(arcana: 'mi', name: 'Ace of Wands', theme: 'Creation', meaning: 'New job, opportunity or business, creativity, and action', imagefile: 'mi-wands01ace.jpg')
Card.create(arcana: 'mi', name: 'Two of Wands', theme: 'Planning', meaning: 'Personal power, strength, success, support, and restlessness', imagefile: 'mi-wands02.jpg')
Card.create(arcana: 'mi', name: 'Three of Wands', theme: 'Leadership', meaning: 'Loan, financial support, goals, focus, and direction', imagefile: 'mi-wands03.jpg')
Card.create(arcana: 'mi', name: 'Four of Wands', theme: 'Achievement', meaning: 'Marriage, partnership, celebration, success, and home', imagefile: 'mi-wands04.jpg')
Card.create(arcana: 'mi', name: 'Five of Wands', theme: 'Conflict', meaning: 'Battles, bickering, pettiness, discord, and squabbles', imagefile: 'mi-wands05.jpg')
Card.create(arcana: 'mi', name: 'Six of Wands', theme: 'Victory', meaning: 'Success, victory, triumph, praise, and recognition', imagefile: 'mi-wands06.jpg')
Card.create(arcana: 'mi', name: 'Seven of Wands', theme: 'Courage', meaning: 'Battles, unfair numbers, in control, and on top of the situation', imagefile: 'mi-wands07.jpg')
Card.create(arcana: 'mi', name: 'Eight of Wands', theme: 'Acceleration', meaning: 'Travel, overseas, speed, movement, and action', imagefile: 'mi-wands08.jpg')
Card.create(arcana: 'mi', name: 'Nine of Wands', theme: 'Discretion', meaning: 'Battling, strength of will, determination, victory, and still fighting', imagefile: 'mi-wands09.jpg')
Card.create(arcana: 'mi', name: 'Ten of Wands', theme: 'Responsibility', meaning: 'Overwhelm, overwork, burdens, and challenge', imagefile: 'mi-wands10.jpg')
Card.create(arcana: 'mi', name: 'Page of Wands', theme: 'Creativity', meaning: 'Message, news, fiery child, and high energy', imagefile: 'mi-wands11page.jpg')
Card.create(arcana: 'mi', name: 'Knight of Wands', theme: 'Creativity', meaning: 'Property, move, new property, action, and speed', imagefile: 'mi-wands12knight.jpg')
Card.create(arcana: 'mi', name: 'Queen of Wands', theme: 'Creativity', meaning: 'Business woman, action, leadership, and resourceful', imagefile: 'mi-wands13queen.jpg')
Card.create(arcana: 'mi', name: 'King of Wands', theme: 'Creativity', meaning: 'Leader, business, action, risk taker, and hard worker', imagefile: 'mi-wands14king.jpg')